# Generated by Django 4.2.17 on 2025-01-15 21:16

from django.db import migrations, models
import urlshort.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=1024)),
                ('short_id', models.CharField(default=urlshort.models.generate_short_id, max_length=6, unique=True)),
            ],
        ),
    ]
