# Generated by Django 4.2.17 on 2025-01-09 16:43

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[recipes.models.min_value], verbose_name='Количество'),
        ),
    ]
