# Generated by Django 4.2.17 on 2025-01-22 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_alter_favorit_options_alter_favorit_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favorited',
            field=models.ManyToManyField(blank=True, related_name='favorited', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.DeleteModel(
            name='Favorit',
        ),
    ]
